// Background service worker — intercepts network requests silently
const TARGET_DOMAINS = [
  'streams.esportex.site',
  'noneserv.pages.dev',
  'embed.streamapi.cc',
  'cdn.streamapi.cc',
  'enteringlacquergiant.com',
  'iptv',
  '.m3u8',
  '.ts',
  '.m3u',
];

let capturedStreams = [];
let captureEnabled = true;

// Load saved streams on startup
chrome.storage.local.get(['capturedStreams'], (result) => {
  if (result.capturedStreams) {
    capturedStreams = result.capturedStreams;
  }
});

// Save function
function saveStreams() {
  chrome.storage.local.set({ capturedStreams: capturedStreams.slice(-500) });
}

// Decode base64 safely
function decodeB64(str) {
  try {
    return atob(str);
  } catch(e) {
    return str;
  }
}

// Intercept all network requests
chrome.webRequest.onCompleted.addListener(
  (details) => {
    if (!captureEnabled) return;
    
    const url = details.url;
    
    // Check if URL matches our targets
    const isTarget = TARGET_DOMAINS.some(d => url.includes(d)) || 
                     url.endsWith('.m3u8') || 
                     url.endsWith('.m3u');
    
    if (!isTarget) return;

    // Extract info
    let channelName = 'unknown';
    let streamUrl = url;
    let siteSource = '';

    // Decode stream.esportex hashes
    if (url.includes('streams.esportex.site') || url.includes('player#')) {
      const hash = url.split('#')[1];
      if (hash) {
        channelName = decodeB64(hash);
        streamUrl = url;
      }
    }

    // Extract tab info
    chrome.tabs.query({active: true, currentWindow: true}, (tabs) => {
      if (tabs[0]) {
        siteSource = tabs[0].url || '';
      }
    });

    // Check response for playlist content
    if (url.endsWith('.m3u8') || url.endsWith('.m3u')) {
      fetch(url, {
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
          'Referer': 'https://streams.esportex.site/',
        }
      })
      .then(r => r.text())
      .then(content => {
        // Check if it's a valid playlist
        if (content.includes('#EXTM3U') || content.includes('#EXTINF')) {
          const entry = {
            id: Date.now() + '_' + Math.random().toString(36).substr(2, 6),
            channel: channelName,
            url: url,
            type: 'm3u8',
            timestamp: new Date().toISOString(),
            source: siteSource,
            content: content.substring(0, 1000),
          };
          capturedStreams.unshift(entry);
          saveStreams();
        }
      })
      .catch(() => {}); // silent fail
    }
  },
  {
    urls: ["<all_urls>"],
    types: ["xmlhttprequest", "media", "script", "other", "sub_frame"]
  }
);

// Listen for messages from popup
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === 'getStreams') {
    sendResponse({ streams: capturedStreams.slice(0, 200) });
  }
  if (request.action === 'clearStreams') {
    capturedStreams = [];
    saveStreams();
    sendResponse({ success: true });
  }
  if (request.action === 'toggleCapture') {
    captureEnabled = !captureEnabled;
    sendResponse({ enabled: captureEnabled });
  }
  if (request.action === 'exportPlaylist') {
    const m3uContent = generateM3U(capturedStreams);
    sendResponse({ playlist: m3uContent });
  }
  return true;
});

function generateM3U(streams) {
  let m3u = '#EXTM3U\n# Playlist generated by Stream Injector 🎬\n';
  streams.forEach(s => {
    if (s.url && s.url.endsWith('.m3u8')) {
      m3u += `#EXTINF:-1,${s.channel || 'unknown'}\n${s.url}\n`;
    }
  });
  return m3u;
}

// Inject content script into iframes
chrome.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
  if (changeInfo.status === 'loading' && tab.url) {
    // Auto-inject into pages with streaming players
    if (tab.url.includes('streams.esportex') || 
        tab.url.includes('player#') ||
        tab.url.includes('streamapi')) {
      // Wait for page to load, then inject
    }
  }
});
